apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-test-1
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
          name: nginx-index-file
          mountPath:/usr/share/nginx/html/
        volumes:
          name: nginx-index-file    
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: app-test-1-ingress
 namespace: app-test-1
 annotations:
   cert-manager.io/issuer: "letsencrypt-production"
spec:
 tls:
   - hosts:
       - apptest1.lukflk.nl
     secretName: wildcard-lukflk
 rules:
   - host: apptest1.lukflk.nl
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: app-test-1-svc
               port:
                 number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
name: index-html-configmap
namespace: app-test-1
data:
index.html:|
<html>
<h1>Yayy! Looks like you found my Kube webpage!</h1>
</br>
</html
<h1>This web page is housed on a Pod running Nginx</h1>
</html                    
