apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-test-1
spec:
  replicas: 2 
  selector:
    matchLabels: 
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: skoopy365/webapp.py:0.1.RELEASE
        ports:
        - name: web
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: app-test-1-ingress
 namespace: app-test-1
 annotations:
   cert-manager.io/issuer: "letsencrypt-production"
spec:
 tls:
   - hosts:
       - webapppy.lukflk.nl
     secretName: wildcard-lukflk
 rules:
   - host: webapppy.lukflk.nl
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: app-test-1-svc
               port:
                 number: 8000
